title: IRAQI Hiba # your name (or website title) here
logo: "/images/logo3.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First year Engineering student at INSEA (Statistics, Applied Economics and Big Data)
  <br><br>
  Passionate about statistics, human genetics and deriving actionable insights from data.
  <br><br>
  <a href="https://www.linkedin.com/in/hiba-iraqi-95a0ba271/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-41WBSMWNRB # your Google Analytics tracking ID here
